### PR TITLE
Updated website to current year.

### PR DESCRIPTION
**Pull request by Tricks1228**

### CODE REVIEW

**Comment by Tricks1228** [comment]
Closed both previous pr's. all changes in them was done here.

**Comment by babbott1000** [comment]
A couple of questions:
Why was PMMI's logo downsized?
Why are some of the resources on the resources page being deleted?
Why are sponsor ranks being removed?
Why is the link on the landing page being changed to TBA?

**Comment by Tricks1228** [comment]
> 

1. As I was updating the sponsors to this year, I didn't realize we had been sponsored by them before
2. We don't use them anymore and it made that page cleaner
3. All of our sponsors this year are giving us around the same amount of money meaning they would all be in platinum. It seemed redundant to have them if every sponsor was in the same tier.
4. The old button led to the about page, having a button to move over 1 tab on the page seemed redundant as well, Leading it to TBA would give people looking at the page more info about our team through our competitions. I was also thinking of possibly making that another button on the page and keeping the old button there.

**Comment by babbott1000** [comment]
1.  Can you modify the PR to remove the changes you made to the logo then, as the older one was higher resolution
2.  Is it a bad idea to leave them there if it has the potential to be useful?  
3.  I think that it's important to recognize the magnitude of the contributions that all of our sponsors are making, and if that means that all of them are in the same tier, that's fine.  Hopefully, we will get more sponsors and it's possible that they'll fall into different tiers.
4.  If people are interested in our team stats I think they would likely look it up themselves.  I think that it's more important to have information about our team on our landing page which I think is what that button is supposed to do.  If you want to revamp the about us page that would be fine to do as well, but I think that is the intent and I think that it makes sense.

**Comment by Tricks1228** [comment]
For the resources page, I think it would be best if we went with my changes but instead of removing the other ones, they were just hidden instead. That way if they are needed in the future, they are still there.

**Comment by WispySparks** [comment]
Remove sponsor ranks, we don't use them anymore.
Update sponsor list.
Change learn more to link to about. Add TBA link to about page.
Add picture for 2023 robot.
Revert deletion on resources.
Add the PDF for the Build Handbook, Mechanical Handbook.
Rename Business Handbook to CAD Handbook but leave it pointing nowhere (it's not done).
Get rid of the blank resources WIP thing.

**Pull request closed without merging**
